[versions]
guava = "33.4.5-android"
kotlin = "2.2.0"
agp = "8.11.0"

[libraries]
guava = { module = "com.google.guava:guava", version.ref = "guava" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }